kind: Service
apiVersion: v1
metadata:
  name: addressSvc
spec:
  type: NodePort
  selector:
    app: addressSvc
  ports:
    port: 9081
    targetPort: 9081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressSvc
  labels:
    app: addressSvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: addressSvc
  template:
    metadata:
      labels:
        app: addressSvc
    spec:
      containers:
        - name: addressSvc
          image: $IMAGE_NAME:$BUILD_NUMBER
          imagePullPolicy: Always
          ports:
            - containerPort: 9081
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              port: 9081
              path: /actuator/health
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              port: 9081
              path: /actuator/health