apiVersion: v1
kind: Service
metadata:
  name: address-spring-service
  labels:
    run: address-spring-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: address-spring